# This is a basic workflow to help you get started with Actions

name: CI


# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
   #group: build-deploy
  group: ${{ format('service-deploy-{0}', join(github.event.pull_request.labels.*.name, '-')) }}
#   group: build-deploy-${{ github.event.number }} 
  cancel-in-progress: true
   
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "sha ${{ github.sha }}"
          echo "ref ${{ github.ref }}"
          echo "event ${{ github.event.number }}"


